version: '3.7'

services:
  omdb-movie-api:
    image: msawastian/omdb_movies_rest_api_v2:2.0.1
    # build: .
    environment:
      - PORT=5000
    ports: 
      - 5000:5000
      # - 9229:9229 
    # command: npm run start:debug
  omdb-movie-api-db:
    image: mysql:5.7
    container_name: "movies-db-api"
    restart: always
    environment:
      MYSQL_DATABASE: omdb-movie-api-dev
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes: 
      - mysql-db:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
volumes: 
    mysql-db:
